const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  DUPLICATE_FIELD: 'DUPLICATE_FIELD',
  SERVER_ERROR: 'SERVER_ERROR',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  TRIP_NOT_FOUND: 'TRIP_NOT_FOUND',
  TRIP_GENERATION_FAILED: 'TRIP_GENERATION_FAILED',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR'
};

const ERROR_MESSAGES = {
  [ERROR_CODES.VALIDATION_ERROR]: 'Validation failed',
  [ERROR_CODES.DUPLICATE_EMAIL]: 'Email already registered',
  [ERROR_CODES.INVALID_CREDENTIALS]: 'Invalid email or password',
  [ERROR_CODES.ACCOUNT_LOCKED]: 'Account temporarily locked due to multiple failed attempts',
  [ERROR_CODES.USER_NOT_FOUND]: 'User not found',
  [ERROR_CODES.INVALID_TOKEN]: 'Invalid token provided',
  [ERROR_CODES.TOKEN_EXPIRED]: 'Token has expired',
  [ERROR_CODES.UNAUTHORIZED]: 'Authentication required',
  [ERROR_CODES.FORBIDDEN]: 'Access forbidden',
  [ERROR_CODES.RESOURCE_NOT_FOUND]: 'Resource not found',
  [ERROR_CODES.DUPLICATE_FIELD]: 'Duplicate field value',
  [ERROR_CODES.SERVER_ERROR]: 'Internal server error',
  [ERROR_CODES.INVALID_REFRESH_TOKEN]: 'Invalid refresh token',
  [ERROR_CODES.TRIP_NOT_FOUND]: 'Trip not found',
  [ERROR_CODES.TRIP_GENERATION_FAILED]: 'Failed to generate trip',
  [ERROR_CODES.EXTERNAL_SERVICE_ERROR]: 'External service unavailable'
};

export { ERROR_CODES, ERROR_MESSAGES };
